# Generated by Django 5.1.4 on 2024-12-18 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRegistartion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentName', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repair_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('component_add_date', models.DateField()),
                ('component_update_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vechical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('vehicle_owner', models.CharField(max_length=255)),
                ('issue_details', models.TextField()),
                ('repair_estimated_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(max_length=255)),
                ('total_cost', models.FloatField()),
                ('payment_issued_date', models.DateField()),
                ('vechical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vechicleapp.vechical')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_cost', models.FloatField()),
                ('created_on', models.DateField()),
                ('description', models.TextField()),
                ('labour_name', models.CharField(max_length=255)),
                ('component_registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vechicleapp.componentregistartion')),
                ('vechical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vechicleapp.vechical')),
            ],
        ),
    ]
