# Generated by Django 5.1.4 on 2024-12-19 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vechicleapp', '0002_alter_componentregistartion_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componentregistartion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
